notifications:
  email:
    recipients:
      - sebastian@jaenicke.org

language: bash

dist: bionic

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y netpbm texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended
  - wget https://github.com/latex2html/latex2html/archive/v2020.tar.gz
  - tar xzf v2020.tar.gz
  - cd latex2html-2020
  - ./configure
  - make && sudo make install
  - cd ..

script:
  - make

